version:3.2

services:
  apache:
  environment:
    image: httpd:2.4
  ports:
    -"80:80"
  volumes:
  - /data/apache:/usr/local/apache2/htdocs/
  networks:
  - minha-rede
networks:
  minha-rede:
    driver: bridge
